spring:
  datasource:
    url: jdbc:mysql://${DATABASE_ADDRESS}/${DATABASE_NAME}?useSSL=false
    name: faf-db
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: false
  boot:
    admin:
      url: ${SPRING_BOOT_ADMIN_URL:http://faf-spring-boot-admin:8030}

logging:
  path: ${LOG_FILE_DIRECTORY:/tmp}

faf-server:
  uid:
    enabled: ${UID_ENABLED:true}
    private-key: ${UID_PRIVATE_KEY}
    link-to-steam-url: ${STEAM_LINK_URL:http://app.faforever.com/faf/steam.php}
  jwt:
    secret: ${JWT_SECRET}
  ladder1v1:
    season: ${LADDER1V1_SEASON}
