faf-server:
  version: #faf-server.version#
  true-skill:
    initial-mean: 1500
    initial-standard-deviation: 500
    beta: 240
    dynamic-factor: 10
    draw-probability: 0.1
  uid:
    link-to-steam-url: http://app.faforever.com/faf/steam.php
  shutdown:
    message: The server has been shut down for maintenance, but should be back online soon. If you experience any problems, please restart your client. We apologize for this interruption.
  api:
    base-url: ${API_BASE_URL}
    client-id: ${API_CLIENT_ID}
    client-secret: ${API_CLIENT_SECRET}
    access-token-uri: ${API_ACCESS_TOKEN_URI}
    max-page-size: 10000
  game:
    stale-game-timeout-seconds: ${STALE_GAME_TIMEOUT_SECONDS:60}

spring:
  application:
    name: FAF Java Server Prototype
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 4
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        dialect: org.hibernate.dialect.MySQL5Dialect
  profiles:
    active: ${SERVER_PROFILE:dev}
  main:
    banner-mode: console

logging:
  level:
    org.springframework: warn
    com.faforever.server: info
    com.zaxxer.hikari: warn
    org.hibernate: warn
    org.eclipse.jetty: warn
    com.faforever.server.config.IntegrationConfig: info
    com.faforever.server.config.LegacyAdapterConfig: info

server:
  port: ${WEB_PORT:8088}

management:
  security:
    enabled: false
